// Curated word lists for username mode — short, friendly, lowercase, letters
// only, so they read well joined with no separator (SwiftFalcon) and survive
// any site's "alphanumeric only" rule. Keep every entry 3–8 characters; the
// length-fitting logic in app.js derives the shortest entry itself.
// Word lists are data — usernames are still assembled with
// crypto.getRandomValues() in app.js.
const CURATED_ADJECTIVES = [
    'able', 'agile', 'amber', 'ancient', 'arctic', 'astral', 'atomic', 'autumn', 'azure',
    'bold', 'brave', 'breezy', 'bright', 'brisk', 'bronze', 'calm', 'candid', 'casual',
    'cheeky', 'chill', 'civic', 'classic', 'clever', 'cloudy', 'cobalt', 'comic', 'cool',
    'cosmic', 'cozy', 'crimson', 'crisp', 'crystal', 'curious', 'daring', 'dapper', 'deep',
    'dizzy', 'double', 'dusty', 'eager', 'early', 'earthy', 'easy', 'ebony', 'electric',
    'elegant', 'emerald', 'epic', 'faint', 'fancy', 'fast', 'fearless', 'fiery', 'fine',
    'firm', 'fizzy', 'fleet', 'floral', 'fluffy', 'flying', 'foggy', 'fond', 'free', 'fresh',
    'frosty', 'funky', 'fuzzy', 'gentle', 'giant', 'giddy', 'gilded', 'glad', 'gleeful',
    'glossy', 'golden', 'good', 'grand', 'gray', 'green', 'groovy', 'handy', 'happy', 'hardy',
    'hasty', 'hearty', 'hidden', 'honest', 'humble', 'hungry', 'icy', 'idle', 'indigo', 'iron',
    'ivory', 'jade', 'jolly', 'jovial', 'joyful', 'jumbo', 'jumpy', 'keen', 'kind', 'lazy',
    'lemon', 'light', 'little', 'lively', 'lofty', 'loud', 'loyal', 'lucky', 'lunar', 'lush',
    'magic', 'major', 'marble', 'mellow', 'merry', 'mighty', 'minty', 'misty', 'modern',
    'modest', 'mossy', 'muddy', 'mystic', 'native', 'neat', 'neon', 'nifty', 'nimble', 'noble',
    'nomad', 'north', 'novel', 'oaken', 'ocean', 'opal', 'orange', 'paper', 'peachy', 'pearl',
    'peppy', 'perky', 'pink', 'plaid', 'plucky', 'plum', 'polar', 'prime', 'proud', 'pure',
    'purple', 'quick', 'quiet', 'quirky', 'rapid', 'rare', 'ready', 'regal', 'retro', 'rich',
    'ripe', 'rocky', 'rosy', 'rowdy', 'royal', 'ruby', 'rugged', 'rustic', 'rusty', 'sable',
    'sacred', 'safe', 'salty', 'sandy', 'sassy', 'scarlet', 'secret', 'serene', 'shady',
    'sharp', 'shiny', 'silent', 'silky', 'silver', 'simple', 'sleek', 'sleepy', 'slick',
    'slim', 'sly', 'smart', 'smoky', 'smooth', 'snappy', 'sneaky', 'snowy', 'snug', 'soft',
    'solar', 'solid', 'sonic', 'spicy', 'spiky', 'spry', 'square', 'starry', 'steady', 'steel',
    'stormy', 'stout', 'sturdy', 'subtle', 'sudden', 'sugar', 'sunny', 'super', 'swift',
    'tall', 'tangy', 'teal', 'tender', 'tidy', 'tiny', 'topaz', 'tough', 'tranquil', 'true',
    'turbo', 'twin', 'ultra', 'umber', 'urban', 'valiant', 'vast', 'velvet', 'vivid', 'vocal',
    'wacky', 'warm', 'wavy', 'wild', 'windy', 'winter', 'wise', 'witty', 'wonder', 'wooden',
    'woolly', 'yellow', 'young', 'zany', 'zesty', 'zippy',
];
const CURATED_NOUNS = [
    'acorn', 'alpaca', 'anchor', 'apple', 'arrow', 'aspen', 'atlas', 'aurora', 'avocado',
    'badger', 'bamboo', 'banjo', 'basil', 'beacon', 'beetle', 'birch', 'bison', 'blossom',
    'bobcat', 'bonsai', 'boulder', 'breeze', 'brook', 'buffalo', 'bunny', 'cactus', 'canyon',
    'canary', 'captain', 'caribou', 'castle', 'cedar', 'cello', 'cheetah', 'cherry',
    'chestnut', 'cinder', 'citrus', 'clover', 'cobra', 'comet', 'compass', 'condor', 'cookie',
    'copper', 'coral', 'cosmos', 'cougar', 'coyote', 'crane', 'cricket', 'crow', 'cypress',
    'daisy', 'dingo', 'dolphin', 'donkey', 'dragon', 'drum', 'dune', 'eagle', 'echo', 'ember',
    'falcon', 'feather', 'fennel', 'fern', 'ferret', 'fiddle', 'finch', 'fjord', 'flame',
    'flint', 'forest', 'fossil', 'fox', 'galaxy', 'garnet', 'gazelle', 'gecko', 'geyser',
    'ginger', 'glacier', 'glider', 'goblin', 'goose', 'gorilla', 'granite', 'grove', 'gull',
    'harbor', 'hawk', 'hazel', 'heron', 'hollow', 'honey', 'horizon', 'hound', 'husky', 'ibis',
    'iceberg', 'iguana', 'island', 'jaguar', 'jasmine', 'jelly', 'jet', 'juniper', 'kayak',
    'kestrel', 'kitten', 'kiwi', 'koala', 'lagoon', 'lantern', 'lark', 'lemur', 'leopard',
    'lily', 'lion', 'lizard', 'llama', 'lobster', 'locust', 'lotus', 'lynx', 'magnet',
    'magpie', 'mammoth', 'mango', 'mantis', 'maple', 'marlin', 'marmot', 'meadow', 'meteor',
    'mink', 'mole', 'monsoon', 'moose', 'moth', 'mustang', 'narwhal', 'nebula', 'nectar',
    'newt', 'nutmeg', 'oak', 'oasis', 'ocelot', 'octopus', 'olive', 'onyx', 'orbit', 'orca',
    'oriole', 'osprey', 'otter', 'owl', 'oyster', 'panda', 'panther', 'parrot', 'pebble',
    'pelican', 'penguin', 'pepper', 'petal', 'phoenix', 'pickle', 'pigeon', 'pilot', 'pine',
    'pixel', 'planet', 'plume', 'pony', 'poppy', 'prairie', 'puffin', 'puma', 'python',
    'quail', 'quartz', 'quill', 'rabbit', 'raccoon', 'raven', 'reef', 'rhino', 'ridge',
    'river', 'robin', 'rocket', 'rover', 'saffron', 'sage', 'salmon', 'sapphire', 'scout',
    'seal', 'sequoia', 'shadow', 'shark', 'sparrow', 'sphinx', 'spruce', 'squid', 'stallion',
    'starling', 'stone', 'stork', 'storm', 'summit', 'sunset', 'swan', 'tadpole', 'talon',
    'tempest', 'thistle', 'thunder', 'tiger', 'timber', 'titan', 'toucan', 'trout', 'tulip',
    'tundra', 'turtle', 'valley', 'vector', 'viking', 'violet', 'viper', 'voyager', 'walnut',
    'walrus', 'wasp', 'willow', 'wizard', 'wolf', 'wombat', 'yak', 'yeti', 'zebra', 'zenith',
    'zephyr',
];
